version: '3.8'
services:
  api:
    build: .
    container_name: 'api-brain-agriculture-williamsumida'
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - brain-agriculture-db

  brain-agriculture-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: brain_agriculture
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    expose:
      - 5432
